### ISSUE TITLE
IOError: cannot identify image 

### ISSUE THREAD

**Issue by taylk808** [tmbdev/ocropy#141]
Getting error:
"IOError: cannot identify image "

When running ocropy on pdf file.  Here is the code I am running.  Anyone had similar issue or suggestions?

```sh
ocropus-nlbin test.pdf -o temp
ocropus-gpageseg 'temp/????.bin.png'
ocropus-rpred -n 'temp/????/??????.bin.png'
ocropus-hocr 'temp/????.bin.png' -o temp.html
ocropus-visualize-results temp
ocropus-gtedit html temp/????/??????.bin.png -o temp-correction.html
```

**Comment by zuphilip** [comment]
As a general remark: Please copy the full error message to make the steps more reproducible for us. 

Here it seems quite clear, that you are trying to directly work on a PDF file instead of some [supported image format](http://pillow.readthedocs.io/en/3.4.x/handbook/image-file-formats.html). Try to convert your PDF first to some image format, e.g.
```
convert test.pdf test.png
```
and then work with then PNG file.

**Comment by kba** [comment]
The problem is that PDF is not supported as input. Since PIL doesn't support reading PDF as image, converting from PDF to an image format as @zuphilip proposed is the best option. @taylk808 Feel free to open a new issue if you have further problems.
