### ISSUE TITLE
A maxheight option for lines

### ISSUE THREAD

**Issue by danvk** [tmbdev/ocropy#15]
I'm running `ocropus-nlbin` and `ocropus-gpageseg` on this image:

![734090b crop](https://cloud.githubusercontent.com/assets/98301/5624599/f887ed08-9536-11e4-9ff5-553a54909498.png)

The first line that comes out of `ocropus-gpageseg` is this:

![010001 bin](https://cloud.githubusercontent.com/assets/98301/5624621/3ca13922-9537-11e4-9328-76645fa2dfd5.png)

i.e. two lines joined into one. Naturally this produces nonsensical output when I run it through `ocropus-rpred`. Admittedly this is a hard case (there's literally one pixel separating the two lines in that image), but it might be nice to have some kind of `maxlineheight` option I could pass to `ocropus-gpageseg` to give it a hint that this is wrong.

Running `ocropus-gpageseg --scale 11 --minscale 11` _does_ split the lines, but I'm reluctant to explicitly set `--scale` for all my images. There are at least two fonts present in the collection, one of which is taller than the other. So it's hard to say the x-height in advance. But I _can_ safely say that if any image of a line is >50 px, then something went wrong.

I'm not sure if such an option would make sense or if there's a better solution, but I wanted to toss the idea out there!

Commands:

```
ocropus-nlbin -n 734090b.crop.png -o book
ocropus-gpageseg -n [--scale 11 --minscale 11] --maxcolseps 0 book/????.bin.png
```

Thanks for the great OCR library!

**Comment by tmbdev** [comment]
I think adding a "maxheight" basically would imply that ocropus-gpageseg consider alternative segmentations ("this line is bigger than 'maxheight', so maybe it should be split into two lines").

However, ocropus-gpageseg just does one-shot segmentation: it looks for everything that looks like a line at the given scale. The only way to get it to consider smaller lines without complete changing its operation is to change the scale parameter. The scale at which lines are found is estimated based on the median size of connected components. The --scale parameter completely overrides automatic scale estimation and may or may not be a good thing to do.

The --hscale and --vscale parameters, on the other hand, let you fine-tune the automatically identified document scale. You might want to use those, maybe --vscale 0.8 

(Long term ocropus-gpageseg should be replaced; it's really just a simple short-term solution that works surprisingly well for what it is. Long term, a page segmenter can be a lot smarter; for example, when considering two alternative segmentations, it can simply decide which one is actually readable and then pick that. LSTM recognizers can also be run directly on the unsegmented page image, so that segmentation falls out of recognition automatically.)

Tom
