### ISSUE TITLE
How Can I Adjust Gpageseg Argument in Receipt To Segment Full Line 

### ISSUE THREAD

**Issue by genzervn** [tmbdev/ocropy#189]
Dear everyone,
when I execute command "ocropus-gpageseg" I want the receipt below just segments to one PNG image. and detect only with one line but Currently, it segments to 2 PNG and ocr with 2 line (**line 1**: GV USED and **line 2**: 50.00)
![image](https://cloud.githubusercontent.com/assets/26240405/23750223/8358ff7e-04fe-11e7-9f7c-fb5dae5b4eb7.png)  
I also used --maxcolseps = 0 but the result is the same.
My expectation is just segment to 1 PNG and OCR text full line (**GV USED 50.00**)
Could you please help me to resolve this issue? 
PS: The full receipt at below and I want to detect with 1 column.  line by line from top to bottom
![image](https://cloud.githubusercontent.com/assets/26240405/23750606/55c87420-0500-11e7-814c-09ca56105a56.png)

Thanks and regards
Duc Dang

**Comment by zuphilip** [comment]
There was a very recent fix which could be connected here, see https://github.com/tmbdev/ocropy/issues/171 . Do you use the newest version? What is the output of `git log` in the ocropy directory for you?

**Comment by zuphilip** [comment]
Okay, now I tried it myself. There is another problem with the reading order.

You can try out the branch https://github.com/tmbdev/ocropy/tree/kassenzettel see also https://github.com/tmbdev/ocropy/pull/190. Does this work now as you expecting it?

**Comment by genzervn** [comment]
Thank a lot for quick supporting (y). As of now the ordering result was better and easy to read so much but honestly it is not my expecting. 
Expecting result in the body:
...
MELANGE OTH 59.00
TOTAL 65.00
GST ON GS 4.25
Gv USED 50.00
...
But actual result
....
59.OO
MELANGE OTH
TOTAL
65.00
GST ON GS
4.25
Gv USED
50.00
...
Seem that it still separates each line to 2 images. but the ordering now is pretty good. do you have any suggestion to reach my expectation?

Thanks

**Comment by zuphilip** [comment]
Are you actually interested in the text or the images for the lines?

The ordering of the textual parts on the same line seems still somtimes to be incorrect. I will look into this.

However, the splitting into two lines, because between the two textual parts there is a lot of spaces, seems more hardcoded in the `gpageseg`. The first 4 lines in your example are just outputed as one line, but the next lines are splitted into two textual parts, see also the debug output:

![_lineseeds](https://cloud.githubusercontent.com/assets/5199995/23788402/8ee266b4-0576-11e7-8381-319f1da5a6b8.png)

I don't know if it is easy to change the algorithmus/code of `gpageseqg` for your goal. Maybe easier could be to work on the hocr-output.

**Comment by genzervn** [comment]
Thanks Philipp,
Whether we have any config to increase space for split part? Which method can I hard-code to change in gpageseg? is it relate to connected component?

Thank you

**Comment by zuphilip** [comment]
> Whether we have any config to increase space for split part? Which method can I hard-code to change in gpageseg? is it relate to connected component?

I am sorry, but I don't know these questions. You can try to understand better what `gpageseg` is doing and then play around a little with the code....

**Comment by genzervn** [comment]
thank you. I'm trying to understand gpageseg. Thank you so much for your support.

**Comment by zuphilip** [comment]
👍 When you have any new insights, then it would be nice, if you share them.
