### ISSUE TITLE
Segmentation Deletes lowercase letters

### ISSUE THREAD

**Issue by tushar1328** [tmbdev/ocropy#307]
## Problem
When the *.pseg.png is generated all the letters which are below written Just like y,g,p, are not detected in the file need the solution to that
See the word Players where lowercase "y" is missing. Need solution to this.
tried changing the --vscale but no changes in the file is being observed. Tried changing the scale but that too failed. any other option for changing the scale. 
### Input File
![0001 bin](https://user-images.githubusercontent.com/11635171/40409974-29e752ce-5e8a-11e8-9496-3cdba4f1cdef.png)

### Output File
![0001 pseg](https://user-images.githubusercontent.com/11635171/40403825-f9ae183a-5e71-11e8-83e4-e592db146055.png)

## Steps to Reproduce (for bugs)

1../run-test

## Your Environment

* Python version: 2.7
* Git revision of ocropy:1 
* Operating System and version: Ubuntu 16.04 LTS

**Comment by lehzwo** [comment]
I think i found the problem but can't think of a solution that is easy to implement by now. 

**The Problem:** 

Your idea to change the value of the scale parameter was fine, since the characters are removed in the function _remove_hlines_.

With an estimated scale of ~31, all objects are deleted that have a width >~310 px. These objects are detected based on connected black pixels.

As I took a closer look at the removed characters I recognized that they are connected to the long horizontal lines. Because of that each horizontal line and its connected characters are interpreted as a single object which is then removed by the _remove_hlines_ function since the objects width is greater than ~310px.

**Comment by kba** [comment]
I would think that it could be solved relatively easily for this particular type of image with a preprocessing step (iterate pixel lines, if X consecutive lines are more than Y percent black, flip the first one white to disconnect letter descenders from that line). Generalizing such a heuristic would probably cause new problems and require extensive testing.
