### ISSUE TITLE
Line detection with different font sizes

### ISSUE THREAD

**Issue by zuphilip** [tmbdev/ocropy#46]
The header line (title) of a document is often written in larger font as the normal text. I experienced that ocropus sometimes cuts a larger font size line into two lines (which are then recognized into nonsense). If the header font is not too much larger (twice seems okay), then the splitting up in lines is okay. But the problem occurs if the header font is 3 times the size of the normal font (36pt and 12pt). E.g. `ocropus-gpageseg` of [0002 bin](https://cloud.githubusercontent.com/assets/5199995/8159957/e0461e1e-136b-11e5-8e22-092bc3ac5a9c.png)

where the headline is split up into three lines:

<img src="https://cloud.githubusercontent.com/assets/5199995/8160051/bada9ff0-136c-11e5-9c17-123052974c11.png" height="40"/>   <img src="https://cloud.githubusercontent.com/assets/5199995/8160053/badfdb82-136c-11e5-9e6b-7c9b73d8f898.png" height="40"/>
<img src="https://cloud.githubusercontent.com/assets/5199995/8160052/baddd10c-136c-11e5-9559-66daae70e1d9.png" height="28"/>

i.e.
______
<img src="https://cloud.githubusercontent.com/assets/5199995/8160051/bada9ff0-136c-11e5-9c17-123052974c11.png" height="40"/>
______
<img src="https://cloud.githubusercontent.com/assets/5199995/8160053/badfdb82-136c-11e5-9e6b-7c9b73d8f898.png" height="40"/>
______
<img src="https://cloud.githubusercontent.com/assets/5199995/8160052/baddd10c-136c-11e5-9559-66daae70e1d9.png" height="28"/>
______
Can the parameters of `ocropus-gpageseg`avoid such a behaviour? Or line detection tweaked in general?

**Comment by tmbdev** [comment]
ocropus-gpageseg assumes that text lines are roughly the same scale. In return, it can detect even touching text lines in noisy documents pretty well. But that's only one of many strategies and possible tradeoffs. Your documents look like they are quite clean but have large variations in font size.

The best way to do text line recognition reliably is probably to run multiple different line detectors and combine their outputs.

As a simple version of that, you could try to run ocropus-gpageseg at different scales, try to recognize all the candidate text lines from the different parameter settings, and throw away those that give gibberish either due to being merged or split up. 

Obviously, that is not going to be cheap. But ultimately, the only arbiter of whether a text line has been correctly segmented is whether you can recognize it, so for general purpose text line segmentation, invoking a recognizer somewhere is necessary.

For Latin script, you can also try to classify individual connected components as text/non-text and then attempt to group those together.

I'm planning on releasing a 2D LSTM based segmenter at some point, but that will still take a while.

**Comment by zuphilip** [comment]
Actually, in my example above the layout segmentation is perfect with `ocropus-gpageseg --vscale 2`.
