### ISSUE TITLE
Using Character Probabilities as Confidence Estimates

### ISSUE THREAD

**Issue by Jdhaimson** [tmbdev/ocropy#47]
Is there a way that I could use the character probabilities output by the LSTM network (and shown in the --show diagrams of rpred) to estimate confidence for a given transcription?  It's unclear how I would actually access those values.

**Comment by tmbdev** [comment]
I've added an option to CLSTMOCR::predict to output the positions of the recognized characters (returned as a vector<int>). You can get the vector of posterior probabilities for all the classes  by looking in CLSTMOCR::net->output

There are many different ways in which you might use these probabilities, which is why there is not default way of outputting them.

(pushing out the changes a little later)

**Comment by isaomatsunami** [comment]
In Python version, where should I look into ?
I want to N-th candidates (and probability) to allow ambiguous search.

**Comment by tmbdev** [comment]
The output sequence is returned by network.forward(inputs); the format is the same as for the C++: each row is a time step, with the columns corresponding to the encoded classes.

**Comment by zuphilip** [comment]
There is now a new parameter in `gpageseg` for that which will produce a `.prob` file for each line. Try for example:
```
ocropus-rpred tests/1175-01002b.png --probabilities
```
