### ISSUE TITLE
Installing Ocropus in Mac Yosemite

### ISSUE THREAD

**Issue by soluna1** [tmbdev/ocropy#70]
Hi,
I want to install Ocropus in mac, I've followed the guidelines from [http://www.danvk.org/2015/01/09/extracting-text-from-an-image-using-ocropus.html] and from Ocropy repository. I managed o do this part: 
   <$brew install python
     $brew install opencv
     $brew install homebrew/python/scipy>
and also this part:
 <$ cd /usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
  $ rm cv.py cv2.so
  $  ln -s /usr/local/Cellar/opencv/2.4.9/lib/python2.7/site-packages/cv.py cv.py
  $  ln -s /usr/local/Cellar/opencv/2.4.9/lib/python2.7/site-packages/cv2.so cv2.so>
But I'm not sure about the instructions provided in the Ocropy Github, see, what section do I use? System-wide or Python Virtual Environment, I'm on mac Yosemite.

To install OCRopus dependencies system-wide:

$ sudo apt-get install $(cat PACKAGES)
$ wget -nd http://www.tmbdev.net/en-default.pyrnn.gz
$ mv en-default.pyrnn.gz models/
$ sudo python setup.py install

Alternatively, dependencies can be installed into a Python Virtual Environment:

$ virtualenv ocropus_venv/
$ source ocropus_venv/bin/activate
$ pip install -r requirements_1.txt
# tables has some dependencies which must be installed first:

$ pip install -r requirements_2.txt
$ wget -nd http://www.tmbdev.net/en-default.pyrnn.gz
$ mv en-default.pyrnn.gz models/

Could someone give a step-by-step guide to follow? I'm a bit lost. thanks!!!

**Comment by lihan** [comment]
I had no problem with installing it using virtual env on El Capitan.

But you do need to ``brew`` to install a few missing dependcies.

**Comment by soluna1** [comment]
I don't have El capital, several people advised me against this apple update. Which dependencies do I have to install?
Thanks

**Comment by lihan** [comment]
@soluna1 

I had two issues that I can recall.

Firstly, you will need to install the latest version of pip, it should be 7.2.1, by the time I tried.

Secondly, refer to https://github.com/PyTables/PyTables/issues/219

You will need to ``brew`` install this package to get ``PyTables`` installed.

BTW, depends on your use case. I've been running El Capitan since they become available, and had no single issue relate to it, the performance has also been **greatly** improved.
